# Generated by Django 3.2.12 on 2022-03-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('client_id', models.CharField(max_length=5)),
                ('client_secret', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=40)),
                ('refresh_token', models.CharField(max_length=40)),
                ('expires_in_minutes', models.IntegerField()),
                ('akun', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='oauth.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('npm', models.CharField(max_length=10)),
                ('akun', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='oauth.useraccount')),
            ],
        ),
    ]
