# Generated by Django 3.2.12 on 2022-03-10 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_useraccount_grant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='login_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires_in_minutes',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
