# Generated by Django 3.2.12 on 2022-03-10 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20220310_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='expires_in_minutes',
            new_name='expires_in_seconds',
        ),
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 10, 49, 13, 615791, tzinfo=utc)),
        ),
    ]
