# Generated by Django 3.2.12 on 2022-03-10 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20220310_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login_time',
            field=models.DateField(default=datetime.datetime(2022, 3, 10, 11, 0, 45, 624080, tzinfo=utc)),
        ),
    ]
